
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/component/Header";
import Footer from "@/component/Footer";
import { Provider } from "react-redux";
import store from "@/lib/store";
import 'react-alice-carousel/lib/alice-carousel.css';
import { FaArrowAltCircleUp } from "react-icons/fa";
import Arrow from "@/component/Arrow";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    template:"Puneri Paltan | %s ",
    default:"Puneri Paltan"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <Header/>
        {children}
        <Arrow />
        <Footer/>
      </body>
    </html>
  );
}
